spring.application.name=employee-service

spring.profiles.active=docker

# ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html